services:
  tg-ai-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm run dev
    volumes:
      - ./.env:/app/.env # Mount the local .env file into the container
    environment:
      - NODE_ENV=development